graph TD
  User((User)) --> Gateway[API Gateway]
  
  Gateway --> AuthService[Identity & Auth Service]
  Gateway --> RideService[Ride Matching Service]
  Gateway --> PaymentService[Payment Service]
  Gateway --> EcoService[Sustainability Service]
  Gateway --> NotifService[Messaging Service]
  Gateway --> ProfileService[User Profile Service]
  Gateway --> VehicleService[Vehicle Verification Service]
  Gateway --> AnalyticsService[Data Analytics Service]

  AuthService --> DB1[(Auth DB)]
  RideService --> DB2[(Ride DB)]
  PaymentService --> DB3[(Payment DB)]
  ProfileService --> DB4[(Profile DB)]
  VehicleService --> DB5[(Vehicle DB)]
  EcoService --> DB6[(Eco DB)]